### ISSUE TITLE
VCS. Time Step Window no longer appears

### ISSUE THREAD

**Issue by stott** [UV-CDAT/uvcdat#2110]
A window with the 'time step' no longer appears in Boxfill, Isofill, isoline or meshfill plots. This makes it very difficult work interactively with these plots. Can you please add these windows back?

**Comment by aashish24** [comment]
@stott sure we can look into it. This is not a GUI issue?

**Comment by aashish24** [comment]
@chaosphere2112 @sankhesh  assigned it to you

**Comment by chaosphere2112** [comment]
@stott Just to make sure, this is the window you're referring to?

![screen shot 2016-08-29 at 10 18 12 am](https://cloud.githubusercontent.com/assets/718512/18060370/b871fae4-6dd2-11e6-9b1f-dddcf21a523b.png)

I've always found it a little touchy to get this open. If this is what you're talking about, I'll work on making it a bit more user-friendly to get it to stay open when you click on the arrow.

**Comment by stott** [comment]
Hi,

The pop up window you show in the screen shot does not appear. And in the
earlier 1.5 version there was a display window with the time-step displayed
continuously (no popup window).

thanks,
Lowell


On Mon, Aug 29, 2016 at 10:24 AM, Sam Fries <notifications@github.com>
wrote:

> @stott
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stott&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=OpCLmq6c0fAduSudj5iKTsNQTcoLCnOxlaXKYJRa2ns&e=>
> Just to make sure, this is the window you're referring to?
>
> [image: screen shot 2016-08-29 at 10 18 12 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_718512_18060370_b871fae4-2D6dd2-2D11e6-2D9b1f-2Ddddcf21a523b.png&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=OUQ-RgvbS8PpmntUAW3I9M7ajUz3Qh4C02i7uKfNNTQ&e=>
>
> I've always found it a little touchy to get this open. If this is what
> you're talking about, I'll work on making it a bit more user-friendly to
> get it to stay open when you click on the arrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2110-23issuecomment-2D243192034&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=4tUynU_mKjAFQyGn6Xw15S17FyhftiIFPzXSvzu6M_c&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwiAHrWiIAbUj9kwN106C4TDwtLecks5qkxXogaJpZM4JtMeY&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=mnm_ganp32qN8Tl7QZtb9WdLsX6osqU3BLZputrpk0Q&e=>
> .
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by stott** [comment]
Hi,

Just checking back to see if there was any update/progress on the window
that displays the time step.

thanks,
Lowell

On Mon, Aug 29, 2016 at 10:24 AM, Sam Fries <notifications@github.com>
wrote:

> @stott
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stott&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=OpCLmq6c0fAduSudj5iKTsNQTcoLCnOxlaXKYJRa2ns&e=>
> Just to make sure, this is the window you're referring to?
>
> [image: screen shot 2016-08-29 at 10 18 12 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_718512_18060370_b871fae4-2D6dd2-2D11e6-2D9b1f-2Ddddcf21a523b.png&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=OUQ-RgvbS8PpmntUAW3I9M7ajUz3Qh4C02i7uKfNNTQ&e=>
>
> I've always found it a little touchy to get this open. If this is what
> you're talking about, I'll work on making it a bit more user-friendly to
> get it to stay open when you click on the arrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2110-23issuecomment-2D243192034&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=4tUynU_mKjAFQyGn6Xw15S17FyhftiIFPzXSvzu6M_c&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwiAHrWiIAbUj9kwN106C4TDwtLecks5qkxXogaJpZM4JtMeY&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=07Ho0sGTIrrUZY_V1_5R3N1Qema4OIrv_GdQqtHaF-k&s=mnm_ganp32qN8Tl7QZtb9WdLsX6osqU3BLZputrpk0Q&e=>
> .
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by chaosphere2112** [comment]
Hey Lowell, sorry, I haven't gotten to this yet. I'll bump it to the top of my list, hopefully should be able to make something happen tomorrow.

**Comment by stott** [comment]
Thanks much.

Lowell

On Thu, Sep 15, 2016 at 9:30 AM, Sam Fries <notifications@github.com> wrote:

> Hey Lowell, sorry, I haven't gotten to this yet. I'll bump it to the top
> of my list, hopefully should be able to make something happen tomorrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2110-23issuecomment-2D247379702&d=DQMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=n1CRLa3q0Eo7jN5N6a7-JMJtimwOFLHWOBO0IwHe6NM&s=hLJlyInr0nB64cglVz1Dw5NSV2TkD0QgOHqusSCWAwc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwugqpFfPW9kW-2DnuL8nxK7xF0grR3ks5qqXKQgaJpZM4JtMeY&d=DQMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=n1CRLa3q0Eo7jN5N6a7-JMJtimwOFLHWOBO0IwHe6NM&s=hJFRS2RJ6YNaUwh4jxSyLnT89PyCGN0mJc9e8taQmNQ&e=>
> .
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by chaosphere2112** [comment]
@stott Ran into some other exciting bugs in the process, but I should have it all squared away Monday.

**Comment by stott** [comment]
Ok thank you Sam

On Friday, September 16, 2016, Sam Fries <notifications@github.com> wrote:

> @stott
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stott&d=DQMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=uB0E5s6HDqJYt1dfPJSrxomsm2lRbX6HuIEcRsW5U80&s=bKtJICYOC0UMg4eVqFWhp1ajtWKRR--6MHxWRDx2Imw&e=>
> Ran into some other exciting bugs in the process, but I should have it all
> squared away Monday.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2110-23issuecomment-2D247730623&d=DQMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=uB0E5s6HDqJYt1dfPJSrxomsm2lRbX6HuIEcRsW5U80&s=6wDOZUIxU9KDkhEZ8j_Ks2So07--Yxgj1jvMgf_lijk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwquiP-2DJm9dSCHvQLMMMD-5FuuoVbDXks5qqyRYgaJpZM4JtMeY&d=DQMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=uB0E5s6HDqJYt1dfPJSrxomsm2lRbX6HuIEcRsW5U80&s=lIvWDq-10Gormfy0W6AT1mDZdVdm8KoahzNwhqyR5UU&e=>
> .
>


-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by chaosphere2112** [comment]
@stott I've pushed the fixes to the repo, but I ran into some issues cutting a new version that you can install using anaconda. If you want to try it out right now, you can do this:

```
git clone git://github.com/UV-CDAT/Vistrails
cd Vistrails
python vistrails/uvcdat.py
```

I'll make sure there's an easy-to-install version tomorrow.

**Comment by stott** [comment]
Thanks Sam,
I'll try the Anaconda install tomorrow after I'm done teaching.

Much appreciated
Lowell

On Monday, September 19, 2016, Sam Fries <notifications@github.com> wrote:

> @stott
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stott&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=M78Ct2ljLeXqb44897jk_7GGgItzKrISX-ibH6BUmiQ&s=JL7Xq7A5YTL7XKgmRdm9YvOLm5-Z3PF8Z0mUs_lN-nc&e=>
> I've pushed the fixes to the repo, but I ran into some issues cutting a new
> version that you can install using anaconda. If you want to try it out
> right now, you can do this:
>
> git clone git://github.com/UV-CDAT/Vistrails
> cd Vistrails
> python vistrails/uvcdat.py
>
> I'll make sure there's an easy-to-install version tomorrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2110-23issuecomment-2D248157750&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=M78Ct2ljLeXqb44897jk_7GGgItzKrISX-ibH6BUmiQ&s=sVwZagsXl1Y6e0WXaiA8QyEgyQbWpi26qIuk43Tp-9g&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwvIqTH74QNdCN2iFMjWGYtPpPdA-2Dks5qrxlJgaJpZM4JtMeY&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=M78Ct2ljLeXqb44897jk_7GGgItzKrISX-ibH6BUmiQ&s=Qq73Umj1FyQi11xMCb04kHZ7RGbLgHQP1-yaVUI-tSs&e=>
> .
>


-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by doutriaux1** [comment]
@stott I uploaded the latest vistrails to anaconda install as follow:
```
conda create -n uvcdat.2016.9.20 -c uvcdat/label/nightly -c uvcdat uvcdat hdf5=1.8.16 pyqt=4.11.3
```

Please let us know if that fixes things for you.

**Comment by stott** [comment]
Charles,

I have just completed the new update as per your email.
However, this did not fix the problem. In fact, the time-step button is
gone altogether. Not only is the time step window gone, the arrow buttons
are also missing now. See the attached screen shot

On Tue, Sep 20, 2016 at 8:42 AM, Charles Doutriaux <notifications@github.com
> wrote:

> @stott
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stott&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=gpxC5v-tkxd8IaFE5j9RRi3xVzIJLQ3I2veF2Tj-OG8&s=o44w70h2kDiOxFRhHnoJlmMOUOk7hqJFNbmLPvHH5O4&e=>
> I uploaded the latest vistrails to anaconda install as follow:
>
> conda create -n uvcdat.2016.9.20 -c uvcdat/label/nightly -c uvcdat uvcdat hdf5=1.8.16 pyqt=4.11.3
>
> Please let us know if that fixes things for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UV-2DCDAT_uvcdat_issues_2110-23issuecomment-2D248341336&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=gpxC5v-tkxd8IaFE5j9RRi3xVzIJLQ3I2veF2Tj-OG8&s=x6qU6IZkyTWkcAb2Mk7vICy2tNVbD_PD3jGEwJY_hgo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEpSwi-5FCpR8LIahwB0b74dOoFquCk0jaks5qr-5F7mgaJpZM4JtMeY&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=eeaFEXh5H-aQ5dyP3sE0ZQ&m=gpxC5v-tkxd8IaFE5j9RRi3xVzIJLQ3I2veF2Tj-OG8&s=s1uB1aZQLG9yQ4joBs0mZmfk4eALvgHJmhi9P-mcSag&e=>
> .
>



-- 
Professor
Department of Earth Sciences
University of Southern California
Los Angeles, CA 90089

**Comment by chaosphere2112** [comment]
@stott Attachments don't come through in GitHub issues; please email Charles or myself directly (Charles is his lastname 1 at llnl.gov, I'm my last name 2 at llnl.gov) or use Github's website to post the image on this issue thread (https://github.com/UV-CDAT/uvcdat/issues/2110)
